module.exports = [
    {
      number: "AF1234",
      from: "Paris (CDG)",
      to: "Fès (FEZ)",
      airline: "Air France",
      time: "14:30",
      status: "À l'heure",
      color: "green",
      duration: "2h30",
      price: "120€",
      terminal: "T2",
      gate: "A12"
    },
    {
      number: "FR5678",
      from: "Londres (LHR)",
      to: "Fès (FEZ)",
      airline: "Ryanair",
      time: "16:45",
      status: "Retardé",
      color: "orange",
      duration: "3h15",
      price: "80€",
      terminal: "T1",
      gate: "B4"
    },
    {
      number: "IB7890",
      from: "Madrid (MAD)",
      to: "Fès (FEZ)",
      airline: "Iberia",
      time: "11:20",
      status: "À l'heure",
      color: "green",
      duration: "1h45",
      price: "95€",
      terminal: "T3",
      gate: "C7"
    },
    {
      number: "LH4321",
      from: "Francfort (FRA)",
      to: "Fès (FEZ)",
      airline: "Lufthansa",
      time: "18:10",
      status: "Annulé",
      color: "red",
      duration: "2h55",
      price: "130€",
      terminal: "T1",
      gate: "D2"
    },
    {
      number: "EK9999",
      from: "Dubaï (DXB)",
      to: "Fès (FEZ)",
      airline: "Emirates",
      time: "22:00",
      status: "À l'heure",
      color: "green",
      duration: "7h10",
      price: "280€",
      terminal: "T4",
      gate: "E10"
    },
    {
      number: "AZ7654",
      from: "Rome (FCO)",
      to: "Fès (FEZ)",
      airline: "Alitalia",
      time: "09:15",
      status: "Retardé",
      color: "orange",
      duration: "2h00",
      price: "110€",
      terminal: "T1",
      gate: "F3"
    },
    {
      number: "TP2020",
      from: "Lisbonne (LIS)",
      to: "Fès (FEZ)",
      airline: "TAP Air Portugal",
      time: "13:25",
      status: "À l'heure",
      color: "green",
      duration: "1h35",
      price: "88€",
      terminal: "T2",
      gate: "G6"
    },
    {
      number: "AT5670",
      from: "Casablanca (CMN)",
      to: "Fès (FEZ)",
      airline: "Royal Air Maroc",
      time: "15:40",
      status: "À l'heure",
      color: "green",
      duration: "1h00",
      price: "70€",
      terminal: "T3",
      gate: "H2"
    },
    {
      number: "TK3344",
      from: "Istanbul (IST)",
      to: "Fès (FEZ)",
      airline: "Turkish Airlines",
      time: "19:50",
      status: "À l'heure",
      color: "green",
      duration: "4h45",
      price: "150€",
      terminal: "T1",
      gate: "I8"
    },
    {
      number: "QA3211",
      from: "Doha (DOH)",
      to: "Fès (FEZ)",
      airline: "Qatar Airways",
      time: "23:30",
      status: "À l'heure",
      color: "green",
      duration: "6h30",
      price: "300€",
      terminal: "T5",
      gate: "J4"
    }
  ];
  